//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservations
    {
        public int ID { get; set; }
        public Nullable<int> GuestID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<System.DateTime> CheckInDate { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        public virtual Guests Guests { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual Rooms Rooms { get; set; }
    }
}
