//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomEquipment
    {
        public int ID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<int> EquipmentID { get; set; }
    
        public virtual AdditionalEquipment AdditionalEquipment { get; set; }
        public virtual Rooms Rooms { get; set; }
    }
}
